title: "PanoAI-Kun | AI Expert & PhD"
description: "Bridging State-of-the-Art Research with Industrial Solutions."
# 这里的 username 记得替换为你实际创建的 Organization 名字
url: "https://PanoAI-Kun.github.io"
baseurl: ""

kramdown:
  math_engine: null

markdown: kramdown
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-katex

katex:
  # 确保在构建时生成静态 HTML 代码，消除客户端闪烁
  render_math: true

collections:
  case_studies:
    output: true
    permalink: /case_studies/:path/